### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by Chaseknis** [Chaseknis/Portfolio_project#10]
# Done so far 🔒 

<img src="https://media3.giphy.com/media/62cXfuNSbdDQb7YuG3/giphy.gif"/>

## Highlights ✅ 

- Linters intergration
- Figma Template UI Design
- Integrated Javascript in the menu for responsiveness

**Comment by roniy68** [comment]
# Well Done So far 🟢 

## great job @Chaseknis 

![gif](https://media.giphy.com/media/LgwoVr7YgUkrC/giphy.gif)

# Checked ✅ 
- Linters error ✔️ 
- JS HTML CSS conventions ✔️ 
- Github Flow ✔️ 

# Optional Suggestion 🧷 
- ***Create a list to dynamically implement the project cards***

**Comment by Donmark2k** [comment]
# STATUS: CHANGES REQUIRED :recycle: 
Hi @Chaseknis  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif">

## Highlights

- Linters are passing :+1: 
- Good use of Github flow :+1: 
- Good PR summary :+1: 

## Required Changes ♻️
Use descriptive class name so that future programmers will understand your code
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
